[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@pyth/=lib/pyth-sdk-solidity/",
    "@pythnetwork/entropy-sdk-solidity/=node_modules/@pythnetwork/entropy-sdk-solidity/"
]

[rpc_endpoints]
zeta_testnet = "${ZETA_TESTNET_RPC}"
zeta_mainnet = "${ZETA_MAINNET_RPC}"

[etherscan]
zeta_testnet = { key = "${ZETA_ETHERSCAN_API_KEY}", url = "https://zetachain-athens.blockscout.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
